name: StatsPE
version: 2.5.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
main: SalmonDE\StatsPE\Base
description: Playerstatistics for your server!
author: SalmonDE
permissions:
 statspe:
  description: Main permission of StatsPE.
  children:
   statspe.cmd:
    description: Main permission of the StatsPE commands.
    children:
     statspe.cmd.fixtable:
       description: Permission for /fixtable.
     statspe.cmd.floatingstats:
      description: Permission for /floatingstats.
     statspe.cmd.stats:
      description: Permission for /stats.
      default: true
     statspe.cmd.stats.advancedinfo:
      description: Enables advanced stats about a player for /stats.
