# Configuration file for StatsPE

# Select your language
Language: English

# Enable Stats: true/false
Stats:
  ClientID: true
  LastIP: false
  UUID: true
  XBoxAuthenticated: false
  FirstJoin: true
  LastJoin: true
  JoinCount: true
  KillCount: true
  K/D: true
  DeathCount: true
  OnlineTime: true
  BlockBreakCount: true
  BlockPlaceCount: true
  ChatCount: true
  ItemConsumeCount: true
  ItemCraftCount: true
  ItemDropCount: true
# Data provider for StatsPE
# It can save it's data in these providers:
# mysql, json
Provider: json
# Time in minutes after which changes are saved
Save-Interval: 20
# Date format, for a further explanation see here: http://php.net/manual/de/function.date.php
Date-Format: "d. M Y"
# mysql settings in case you're using it
MySQL:
    host: "example.net:3306"
    username: "ExampleUser"
    password: "123456789"
    database: "StatsPE"
# Enables self updating of the plugin
Auto-Update: true
