# Configuration file for StatsPE

# Enable Stats: true/false
Stats:
  ClientID: true
  LastIP: false
  UUID: true
  XBoxAuthenticated: false
  FirstJoin: true
  LastJoin: true
  JoinCount: true
  KillCount: true
  K/D: true
  DeathCount: true
  OnlineTime: true
  BlockBreakCount: true
  BlockPlaceCount: true
  ChatCount: true
  BedEnterCount: true
  EatCount: true
  CraftCount: true
  DroppedItemsCount: true
  BowUseCount: true
# Data provider for StatsPE
# It can save it's data in these providers:
# mysql, json
Provider: json
# mysql settings in case you're using it
MySQL:
    host: "example.net:3306"
    username: "ExampleUser"
    password: "123456789"
    database: "StatsPE"
# Enables self updating of the plugin
Auto-Update: true
